/**
 * Backs up the live Turso database to a local SQL file you can keep.
 *
 *   TURSO_URL=libsql://... TURSO_AUTH_TOKEN=... node scripts/backup-turso.mjs
 *   node scripts/backup-turso.mjs my-backup.sql      # custom filename
 *
 * Easier alternative: sign in to the admin panel and press "Download backup"
 * on the dashboard — same file, works from a phone, no tokens to handle.
 *
 * Why this exists: Turso's free plan only keeps 1 day of point-in-time
 * restore, so a mistake noticed a week later cannot be undone. Run this
 * occasionally (or before big content edits) and keep the file somewhere safe.
 *
 * The output is plain SQL — restore it by pasting into Turso's SQL console or
 * running it against a fresh database. Each table is cleared by the file
 * itself, so no manual DELETE step is needed.
 *
 * Admin accounts, sessions and security logs are NOT included, so the file
 * carries no credentials and is safe to store.
 *
 * The SQL is generated by src/lib/backup.ts — the same code the admin download
 * button uses, so the two can never drift apart.
 */
import fs from 'node:fs';
import Database from 'libsql';
import { buildBackupSql, backupFilename } from '../dist/lib/backup.js';

const URL = (process.env.TURSO_URL || '').trim();
const TOKEN = (process.env.TURSO_AUTH_TOKEN || '').trim();
const OUT = process.argv[2] || backupFilename();

if (!URL) {
  console.error('TURSO_URL is not set.\n');
  console.error('Usage:');
  console.error('  TURSO_URL=libsql://... TURSO_AUTH_TOKEN=... node scripts/backup-turso.mjs\n');
  console.error('Or just press "Download backup" on the admin dashboard.');
  process.exit(1);
}

const db = new Database(URL, { authToken: TOKEN });
const { sql, rows, tables } = buildBackupSql(db);

fs.writeFileSync(OUT, sql, 'utf8');

const kb = (fs.statSync(OUT).size / 1024).toFixed(0);
console.log(`Backup written: ${OUT} (${kb} KB, ${rows} rows)\n`);
for (const { table, rows: n } of tables) {
  if (n) console.log(`  ${table.padEnd(24)} ${n}`);
}
console.log('\nKeep this file somewhere outside the server.');
